# -*- coding: utf-8 -*-
"""Numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MQZHnEkofiSNC0srQZ1XwMYl9shl7oMP
"""

pip install numpy

import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
print("One dimensional array:", arr1, sep='\n', end='\n\n')

arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("Two dimensional array:", arr2, sep='\n', end='\n\n')

arr3 = np.array([[[1, 2], [3,4]], [[5, 6], [7, 8]]])
print("Three dimensional array:", arr3, sep='\n', end='\n\n')

zeros = np.zeros((3, 4))
print("zeros:", zeros)

ones = np.ones((3, 4))
print("ones:", ones)

identity = np.eye(4)
print(identity)

fullarray = np.full((10, 2), 20)
print(fullarray)

range_arr = np.arange(10, 0, -1)
print(range_arr)

range_arr = np.arange(2, 51, 2)
print(range_arr)

lin_space = np.linspace(0, 10, 5)
print(lin_space)

lin_space = np.linspace(0, 100, 5)
print(lin_space)

a = ['Python', 'HTML', 'CSS', 'JS', 'React']
random_arr = np.random.choice(a, 3)
print(random_arr)

random_arr = np.random.randint(1, 20, (2,3))
print(random_arr)

random_arr = np.random.randint(1, 20, (2))
print(random_arr)

random_arr = np.random.randint(20, 25)
print(random_arr)

random_arr = np.random.rand(4)
print(random_arr)

random_arr = np.random.randint(100)
print(random_arr)

np.random.seed(10)
random_arr = np.random.randint(100)
print(random_arr)

arr = np.array([[1,2], [3,4], [5,6], [7,8], [9,0], [0,1]])
print(arr.shape)

reshaped = arr.reshape(3,4)
print(reshaped)

a = np.array([[1,2,3,4], [5,6,7,8]])
flattened = a.flatten()
print(flattened)

trasposed = a.T
print(trasposed)

arr = np.array([1, 2, 3, 4, 5])
print(arr[0])
print(arr[-1])
print(arr[1:4])
print(arr[:3])
print(arr[::2])

matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(matrix[0:3, 1])
print(matrix[1:3, 2])
print(matrix[0:2, 0:2])
print(matrix[1:, 1:3])

arr = np.array([4, 9, 16, 25, 64])
print(arr+10)
print(arr*2)
print(arr*0.5)

print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.var(arr))
print(np.std(arr))
print(np.max(arr))
print(np.min(arr))

arr = np.array([1,2,3,4,5])
print(np.cumsum(arr))
print(np.cumprod(arr))

arr = np.array([1,2,3,4,5,6,7,8,9,0])
print(arr%2==0)
print(arr[arr%2!=0])

arr = np.array([4,5,6,1,3,7,9,1,2,5,6,8,3,7,1])
sorted_arr = np.sort(arr)
print(sorted_arr)

unq = np.unique(arr)
print(unq)

arr = np.array([1,2,3])
view_arr = arr.view()
view_arr[0] = 100
print(view_arr)
print(arr)

copy_arr = arr.copy()
copy_arr[0] = 10
print(copy_arr)
print(arr)

a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])
print(np.dot(a,b))

print(np.linalg.det(a))
print(np.linalg.inv(a))

eigenvalues, eigenvectors = np.linalg.eig(a)
print(eigenvalues)
print(eigenvectors)

c = np.array([5,11])
sol = np.linalg.solve(a,c)
print(sol)

a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])
ver_stack = np.vstack((a,b))
hori_stack = np.hstack((a,b))
print(ver_stack)
print(hori_stack)

split_arr = np.split(np.array([1,2,3,4,5,6]), 3)
print(split_arr)