from datetime import date, time, datetime, timedelta

# today = date.today()
# print("Today Date: ", today)
# print("Today Day: ", today.day)
# print("Today Month: ", today.month)
# print("Today Year: ", today.year)
# print("WeekDay: ", today.weekday())

# year, month, data = list(map(int,input('[YYYY-MM-DD]: ').split('-')))
# print(date(year, month, data))

# t = time(14, 30, 15)
# print("Time: ", t)
# print("Hour: ", t.hour)
# print("Minute: ", t.minute)
# print("Second: ", t.second)

# dt = datetime.now()
# # print(dt)
# # print(dt.strftime('%D-%m-%Y'))
# print(dt.day)
# print(dt.month)
# print(dt.year)
# print(dt.weekday())
# print(dt.hour)
# print(dt.minute)
# print(dt.second)
# print(dt.strftime('%D-%m-%Y %H:%M:%S'))
# print(dt.strftime('%D-%m-%Y %H:%M:%S %p'))
# print(dt.strftime('%d %b %Y %H:%M:%S %p'))
# print(dt.strftime('%d %B %Y %H:%M:%S %p'))
# print(dt.strftime('%a %d %Y %H:%M:%S %p'))
# print(dt.strftime('%A %d %Y %H:%M:%S %p'))

t = date.today()
n = datetime.now()
t7 = t + timedelta(days=7)
t5 = t - timedelta(days=5)
n15 = n + timedelta(minutes=15)

print(t, t7)
print(t, t5)
print(n, n15)